#!/usr/bin/env bash
# Displays the file `/etc/passwd`with below conditions:
#   Only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"

